# 删除倍率
[[rename_node]]
match = "\s?\(?((x|X)?(\d+)(\.?\d+)?)((\s?倍率?)|(x|X))\)?|(\*\d+\.?\d+?)?"
replace = ""

[[rename_node]]
match = "RUS"
replace = "俄罗斯"

[[rename_node]]
match = "AUS?"
replace = "澳大利亚"

[[rename_node]]
match = "IDN"
replace = "印度尼西亚"

[[rename_node]]
match = "FRA?"
replace = "法国"

[[rename_node]]
match = "DEU?"
replace = "德国"

[[rename_node]]
match = "ESP"
replace = "西班牙"

[[rename_node]]
match = "ISL"
replace = "冰岛"

[[rename_node]]
match = "DNK"
replace = "丹麦"

[[rename_node]]
match = "CAN"
replace = "加拿大"

[[rename_node]]
match = "GBR|UK"
replace = "英国"

[[rename_node]]
match = "VNM"
replace = "越南"

[[rename_node]]
match = "THA"
replace = "泰国"

[[rename_node]]
match = "TUR"
replace = "土耳其"

[[rename_node]]
match = "POL"
replace = "波兰"

[[rename_node]]
match = "NLD"
replace = "荷兰"

[[rename_node]]
match = "HKG?|Hong ?Kong"
replace = "香港"

[[rename_node]]
match = "SGP?|狮城|Singapore"
replace = "新加坡"

[[rename_node]]
match = "TWN?|Taiwan"
replace = "台湾"

[[rename_node]]
match = "USA?"
replace = "美国"

[[rename_node]]
match = "JPN?|Japan"
replace = "日本"

[[rename_node]]
match = "IND?"
replace = "印度"

[[rename_node]]
match = "KR|KOR"
replace = "韩国"

[[rename_node]]
match = "ZJ(-P)?"
replace = "丽水"

[[rename_node]]
match = "DEU?"
replace = "德国"

[[rename_node]]
match = "GZCM-香港|GZCM-P|GZCM|广移中继|GZ-P"
replace = "广移"

[[rename_node]]
match = "CN2-香港"
replace = "CN2"

[[rename_node]]
match = "CSCU-香港|CSCU|CUCU|HZCU-香港|HZCU|SHCU|河南联通|湖南联通|湖南聯通"
replace = "联通"

[[rename_node]]
match = "香港IX"
replace = "HKIX"

[[rename_node]]
match = "香港T"
replace = "HKT"

[[rename_node]]
match = "Relay"
replace = "中继"

[[rename_node]]
match = "BGP-香港"
replace = "BGP"


# 中括号内容修正,移除,无用文本移除(mbps)
[[rename_node]]
match = "\[IEPL\]"
replace = "IEPL"

[[rename_node]]
match = "(\（|\『|\[|\【).*?(\）|\』|\]|\】)"
replace = ""


# kocyyds
[[rename_node]]
match = "(IPLC)(.*)专线\|.*"
replace = "$2$1"


# DH_IEPL
[[rename_node]]
match = "^([^\x00-\xff]{2,3})(.*)\|1?\.?0?\|(SH)?(IEPL|广移|9929|丽水|镇江|CN2|联通)?(\|)?DC(\d)"
replace = "$1${4:-} $6"


# LinkCube
[[rename_node]]
match = "(专线) (深)圳-(香)?(.)(本|国|湾|加坡|兰|西|拿大|罗斯|耳其|来西亚|洲|度|大利)? (\d+)"
replace = "$2$4-$1 $6"


# PY_Space
[[rename_node]]
match = "([A-Z]{2})(.+) \| (.*) \| (.*)"
replace = "$3-$2|$4"


# ABCloud

# TomLink
[[rename_node]]
match = "(.*)(IEPL|中转)-(\d\d)(\s+)?\|(\s+)?$"
replace = "$1$2 $3"

