version: "2.0"
services:
  jdql:
    image: whyour/qinglong:2.10.13
    container_name: jdql
    restart: always
    network_mode: bridge
    tty: true
    volumes:
      - ~/jdql/config:/ql/config
      - ~/jdql/log:/ql/log
      - ~/jdql/db:/ql/db
      - ~/jdql/repo:/ql/repo
      - ~/jdql/deps:/ql/deps
      - ~/jdql/raw:/ql/raw
      - ~/jdql/scripts:/ql/scripts
      - ~/jdql/jbot:/ql/jbot
    ports:
      - 5789:5700
    environment:
      - ENABLE_HANGUP=true
      - ENABLE_WEB_PANEL=true
  
   
