#WordPress博客
version: '3.1'
services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 8888:80   #8088自定义端口
    environment:
      WORDPRESS_DB_HOST: db1:3306
      WORDPRESS_DB_USER: dbusername
      WORDPRESS_DB_PASSWORD: dbpassword
      WORDPRESS_DB_NAME: dbname
    volumes:
      - /var/www/wordpress:/var/www/html
  db1:
    image: mariadb
    restart: always
    ports:
      - 10086:3306  #数据库可不映射端口,如无需外部管理,注释ports与此行
    container_name: wpmariadb
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbusername
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - /var/www/db:/var/lib/mysql
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
        - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: mariadb wordpress watchtower --cleanup --schedule "0 0 4 * * *" 
volumes:
  wordpress:
  db1:
