#极光中转面板 (暂未测试)
#https://github.com/Aurora-Admin-Panel/deploy readme查看使用方法
version: '3.7'
services:
  worker:
    image: leishi1313/aurora-admin-backend:latest
    restart: always
    container_name: jgworker
    command: bash worker.sh
    environment:
      TZ: 'Asia/Shanghai'
      ENABLE_SENTRY: 'yes'
      DATABASE_URL: 'postgresql://aurora:AuroraAdminPanel321@postgres:5432/aurora'
      TRAFFIC_INTERVAL_SECONDS: 600
      DDNS_INTERVAL_SECONDS: 120
    volumes:
      - $HOME/.ssh/id_rsa:/app/ansible/env/ssh_key
      - app-data:/app/ansible/priv_data_dirs
    depends_on:
      - redis
  backend:
    image: leishi1313/aurora-admin-backend:latest
    restart: always
    container_name: jgbackend
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; alembic upgrade heads && python app/main.py"
    environment:
      TZ: 'Asia/Shanghai'
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://aurora:AuroraAdminPanel321@postgres:5432/aurora'
      ENABLE_SENTRY: 'yes'
      SECREY_KEY: 'AuroraAdminPanel321'
    volumes:
      - app-data:/app/ansible/priv_data_dirs
    depends_on:
      - postgres
      - redis
  nginx:
    image: leishi1313/aurora-admin-frontend:latest
    restart: always
    container_name: jgnginx
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - 8000:80
    depends_on:
      - backend
  redis:
    image: redis
    container_name: jgredis
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
  postgres:
    image: postgres:13-alpine
    container_name: jgpostgres
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      POSTGRES_USER: aurora
      POSTGRES_PASSWORD: AuroraAdminPanel321
      POSTGRES_DB: aurora
    volumes:
      - db-data:/var/lib/postgresql/data
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    environment:
        - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: mariadb wordpress watchtower --cleanup --schedule "0 0 4 * * *" 
volumes:
  db-data:
  app-data: