version: '3.1'

#docker run -d --restart=always --name=reader -e "SPRING_PROFILES_ACTIVE=prod" -v $(PWD)/logs:/logs -v $(PWD)/storage:/storage -p 8080:8080 hectorqin/reader
# 多用户版
#docker run -d --restart=always --name=reader -v $(PWD)/logs:/logs -v $(PWD)/storage:/storage -p 8080:8080 hectorqin/reader java -jar /app/bin/reader.jar --spring.profiles.active=prod --reader.app.secure=true --reader.app.secureKey=管理密码 --reader.app.inviteCode=注册邀请码
# 多用户版 使用环境变量
#docker run -d --restart=always --name=reader -e "SPRING_PROFILES_ACTIVE=prod" -e "READER_APP_SECURE=true" -e "READER_APP_SECUREKEY=管理密码" -e "READER_APP_INVITECODE=注册邀请码" -v $(PWD)/logs:/logs -v $(PWD)/storage:/storage -p 8080:8080 hectorqin/reader

#reader 在线阅读 
# 作者GitHub : https://github.com/hectorqin/reader
# 本人在线演示(服务器位于日本) : https://reader.nxnow.online ,账号密码均为guest,也可自行创建后添加书源
# 书源参考 : https://github.com/NZESupB/ReadSource ,书源合集下选一个合集进入网页后, Ctrl+S 保存至本地后导入网站即可
services:
# 自用版
#  read_own:
#    image: hectorqin/reader
#    container_name: reader_own
#    restart: always
#    ports:
#      - 4395:8080
#    volumes:
#      - /home/reader/log:/log
#      - /home/reader/storage:/storage
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
# 多用户版
  read_all:
    image: hectorqin/reader
    container_name: reader #容器名 可自行修改
    restart: always
    ports:
      - 4396:8080 #端口映射
    volumes:
      - /home/reader/log:/log #log映射目录 /home/reader/log 可自行修改
      - /home/reader/storage:/storage #数据映射目录 /home/reader/storage 可自行修改
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - READER_APP_SECURE=true
      - READER_APP_SECUREKEY=953608159  #管理员密码  可自行修改
      #- READER_APP_INVITECODE=123456 #注册邀请码,如需要取消注释 可自行修改

   