name: Modify M3U File

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  fetch-and-replace:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch and replace
        run: |
          curl -sL https://raw.githubusercontent.com/benmoose39/YouTube_to_m3u/main/youtube.m3u | sed -e 's/raw.githubusercontent.com/raw.nxnow.top/g' -e 's/manifest.googlevideo.com/ee.nxnow.top:4436/g' > ytb.m3u

      - name: Delete current release assets
        uses: 8Mi-Tech/delete-release-assets-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: YouTubeM3U
          deleteOnlyFromDrafts: false

      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: YouTubeM3U
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          cat > release.txt << 'EOF'
          Release created at  ${{ env.BUILDTIME }}
          <br>
          [Youtube to m3u / Source](https://raw.githubusercontent.com/benmoose39/YouTube_to_m3u/main/youtube.m3u)
          EOF

      - name: Upload Prerelease
        uses: softprops/action-gh-release@v1
        if: ${{  success() }}
        with:
          tag_name: YouTubeM3U
          files: |
            ytb.m3u
          prerelease: true
          generate_release_notes: true
          body_path: release.txt
